---
kind: pipeline
name: staging-backend

trigger:
  branch:
  - staging
  paths:
    include:
    - "modules/web_app/backend/**"
    exclude:
    - ".gitignore"

environment:
  REGISTRY: 221423461835.dkr.ecr.ap-southeast-1.amazonaws.com
  REPO: topdup-prod-backend

steps:
- name: build backend images
  image: plugins/ecr
  pull: if-not-exists
  settings:
    tags: ${DRONE_COMMIT_SHA:0:6}
    access_key:
      from_secret: ciuser_key_id #ciuser is the IAM user in AWS
    secret_key:
      from_secret: ciuser_secret_access_key
    repo: topdup-prod-backend
    registry: ${REGISTRY}
    region: ap-southeast-1
    dockerfile: modules/web_app/backend/Dockerfile

- name: render nomad.hcl
  image: alpine
  environment:
    TAG: ${DRONE_COMMIT_SHA:0:6}
    POOL_HOST:
      from_secret: staging_postgresql_host
    POOL_DB_NAME:
      from_secret: staging_postgresql_dbname
    POOL_USR:
      from_secret: staging_postgresql_user
    POOL_PWD:
      from_secret: staging_postgresql_password
  commands:
    - apk add gettext
    - cat modules/web_app/backend/nomad.hcl | envsubst > modules/web_app/backend/nomad.rendered.hcl
    - cat modules/web_app/backend/nomad.rendered.hcl

- name: deploy to Nomad
  image: loq9/drone-nomad
  network_mode: host
  settings:
    addr: http://100.64.25.41:4646
    template: modules/web_app/backend/nomad.rendered.hcl
    token:
      from_secret: nomad_deployer_token

- name: sent notification to slack
  image: plugins/slack
  settings:
    webhook: 
      from_secret: slack_incoming_webhook
    channel: build-notifications
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}
